# k0sctl configuration for k0rdent management cluster
# Generated by Terraform for engineer: ${cluster_name}

apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: ${cluster_name}
spec:
  k0s:
    version: "${k0s_version}"
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: ${cluster_name}
      spec:
        api:
          # Allow connections from anywhere in VPC
          sans:
%{ for ip in node_ips ~}
            - "${ip}"
%{ endfor ~}
        network:
          # Must match the live cluster config in mgmt-cloud-init.yaml (calico/vxlan)
          provider: calico
          calico:
            mode: vxlan
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
        telemetry:
          enabled: false
  hosts:
%{ for i, ip in node_ips ~}
    - role: ${i == 0 ? "controller+worker" : "controller+worker"}
      ssh:
        address: "${ip}"
        user: ${ssh_user}
        port: 22
        keyPath: "${ssh_key_path}"
      installFlags:
        - --enable-worker
%{ if i == 0 ~}
      privateAddress: "${ip}"
%{ endif ~}
%{ endfor ~}
